version: '3.3'
services:
  web:
    env_file:
    - .env
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: hamelin_php_74
    depends_on:
      - db
    ports:
      - 8130:80
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
  db:
    container_name: hamelin_mysql8
    env_file:
    - .env
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
    - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 6035:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./php/conf_server/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    env_file:
    - .env
    container_name: hamelin_phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8131:80
    depends_on:
      - db 